import logging
from datetime import datetime
import pytz
import random
import discord
from discord.ext import commands, tasks
from discord import app_commands
from cognitas.core.state import GameState

logger = logging.getLogger("cognitas.cogs.misc")

class MiscCog(commands.Cog):
    """
    Miscellaneous utilities, including Server Clocks and maintenance.
    """
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.update_clocks.start()

    def cog_unload(self):
        self.update_clocks.cancel()

    @app_commands.command(name="tz", description="GM: Crea un canal de voz fijo que muestra la hora en vivo.")
    @app_commands.describe(region="La zona horaria que deseas mostrar")
    @app_commands.choices(region=[
        app_commands.Choice(name="🇪🇸 España", value="Europe/Madrid"),
        app_commands.Choice(name="🇦🇷 Argentina", value="America/Argentina/Buenos_Aires"),
        app_commands.Choice(name="🇨🇱 Chile", value="America/Santiago"),
        app_commands.Choice(name="🇲🇽 México", value="America/Mexico_City"),
        app_commands.Choice(name="🇨🇴 Colombia/Perú", value="America/Bogota"),
        app_commands.Choice(name="🇻🇪 Venezuela", value="America/Caracas"),
        app_commands.Choice(name="🌐 UTC", value="UTC")
    ])
    @app_commands.default_permissions(administrator=True)
    async def create_clock(self, interaction: discord.Interaction, region: app_commands.Choice[str]):
        await interaction.response.defer(ephemeral=True)

        if not hasattr(self.bot, "game_state"):
            await interaction.followup.send("❌ Inicializa la partida primero.")
            return

        state: GameState = self.bot.game_state
        if "clock_channels" not in state.discord_setup:
            state.discord_setup["clock_channels"] = {}

        # 1. Check if we already have a clock for this region to avoid spam
        if region.value in state.discord_setup["clock_channels"]:
            await interaction.followup.send(f"⚠️ Ya existe un reloj para {region.name}. Si lo borraste, usa `/wipe_clocks` primero.")
            return

        # 2. Get current time
        try:
            tz = pytz.timezone(region.value)
            current_time = datetime.now(tz).strftime("%H:%M")
        except pytz.UnknownTimeZoneError:
            await interaction.followup.send("❌ Error interno: Zona horaria no válida.")
            return

        # 3. Create the locked Voice Channel
        guild = interaction.guild
        overwrites = {
            guild.default_role: discord.PermissionOverwrite(connect=False, view_channel=True)
        }
        
        # We extract the flag emoji from the name string for aesthetics
        flag = region.name.split(" ")[0]
        channel_name = f"{flag} {current_time}"

        try:
            # We place it at the top of the server (position 0)
            clock_channel = await guild.create_voice_channel(
                name=channel_name, 
                overwrites=overwrites,
                position=0,
                reason="Clock channel generated by /tz"
            )
            
            # 4. Save to our database instantly to prevent orphaned channels on crash
            state.discord_setup["clock_channels"][region.value] = clock_channel.id
            self.bot.storage.save_state(state)
            
            await interaction.followup.send(f"✅ Reloj creado exitosamente: {clock_channel.mention}")
            logger.info(f"Clock channel created for {region.value} ({clock_channel.id})")
            
        except discord.Forbidden:
            await interaction.followup.send("❌ No tengo permisos para crear canales de voz.")

    @tasks.loop(minutes=15.0)
    async def update_clocks(self):
        """Updates all registered clock channels every 15 minutes to strictly obey Discord API limits."""
        if not hasattr(self.bot, "game_state"):
            return

        state: GameState = self.bot.game_state
        clock_dict = state.discord_setup.get("clock_channels", {})

        for region_val, channel_id in list(clock_dict.items()):
            channel = self.bot.get_channel(channel_id)
            if not channel:
                # If the GM manually deleted the channel, remove it from our memory and save
                del clock_dict[region_val]
                self.bot.storage.save_state(state)
                logger.info(f"Clock channel {channel_id} not found. Removing from registry and saving state.")
                continue

            try:
                tz = pytz.timezone(region_val)
                new_time = datetime.now(tz).strftime("%H:%M")
                
                # We need to extract the flag/prefix from the current name to keep it
                # Assuming format: "🇪🇸 15:30"
                parts = channel.name.split(" ")
                prefix = parts[0] if len(parts) > 1 else "🕒"
                
                new_name = f"{prefix} {new_time}"
                
                # Only edit if the time actually changed (saves API calls)
                if channel.name != new_name:
                    await channel.edit(name=new_name)
                    logger.debug(f"Clock {region_val} updated to {new_name}")
                    
            except discord.RateLimited:
                logger.warning(f"Rate limited while updating clock {region_val}. Skipping this cycle.")
            except Exception as e:
                logger.error(f"Failed to update clock {region_val}: {e}")

    @update_clocks.before_loop
    async def before_update_clocks(self):
        await self.bot.wait_until_ready()

    @app_commands.command(name="dice", description="Lanza un dado de determinado número de caras.")
    @app_commands.describe(sides="Numero de caras (default = 6).")
    async def roll_dice(self, interaction: discord.Interaction, sides: int = 6):
        if sides < 2:
            await interaction.response.send_message("❌ El dado debe tener al menos dos caras.", ephemeral=True)
            return
            
        result = random.randint(1, sides)
        await interaction.response.send_message(f"🎲 {interaction.user.mention} lanzó un dado de **d{sides}** caras y obtuvo un: **{result}**")

    @app_commands.command(name="coin", description="Lanza una o más monedas.")
    @app_commands.describe(amount="Número de monedas a lanzar (default = 1).")
    async def flip_coin(self, interaction: discord.Interaction, amount: int = 1):
        if amount < 1 or amount > 20:
            await interaction.response.send_message("❌ Solo puedes lanzar entre 1 y 20 monedas.", ephemeral=True)
            return

        # List comprehension for efficiency
        results = [random.choice(["Cara", "Cruz"]) for _ in range(amount)]
        
        if amount == 1:
            await interaction.response.send_message(f"🪙 {interaction.user.mention} ha lanzado una moneda y salió: **{results[0]}**")
        else:
            formatted_results = ", ".join(results)
            await interaction.response.send_message(f"🪙 {interaction.user.mention} ha lanzado {amount} monedas:\n**{formatted_results}**")

    @app_commands.command(name="choose", description="Elige un jugador al azar.")
    @app_commands.choices(mode=[
        app_commands.Choice(name="Solo Vivos.", value="alive"),
        app_commands.Choice(name="Solo Muertos.", value="dead"),
        app_commands.Choice(name="Todos los jugadores.", value="all")
    ])
    async def player_roulette(self, interaction: discord.Interaction, mode: app_commands.Choice[str]):
        if not hasattr(self.bot, "game_state"):
            await interaction.response.send_message("❌ El juego no está inicializado.", ephemeral=True)
            return

        state: GameState = self.bot.game_state
        players = list(state.players.values())
        
        if not players:
            await interaction.response.send_message("❌ No hay jugadores registrados.", ephemeral=True)
            return

        # Filter based on selected mode
        pool = []
        if mode.value == "alive":
            pool = [p for p in players if p.is_alive]
        elif mode.value == "dead":
            pool = [p for p in players if not p.is_alive]
        else:
            pool = players

        if not pool:
            await interaction.response.send_message(f"❌ No se han encontrado jugadores con el criterio '{mode.name}'", ephemeral=True)
            return

        chosen_player = random.choice(pool)
        await interaction.response.send_message(f"🎯 Gira la ruleta de jugadores ({mode.name}): El jugador elegido es <@{chosen_player.user_id}>!")

async def setup(bot: commands.Bot) -> None:
    await bot.add_cog(MiscCog(bot))